# Generated by Django 5.1.7 on 2025-03-18 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_type', models.CharField(choices=[('PC', 'Промо-Код'), ('BO', 'Бонусы'), ('BC', 'Баллы')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User_benefits_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_benefits_quantity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_benefits_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.benefits')),
            ],
        ),
    ]
