# Generated by Django 5.1.7 on 2025-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_benefits_data',
            name='user_benefits_type',
        ),
        migrations.AddField(
            model_name='user_benefits_data',
            name='user_benefits_type',
            field=models.ManyToManyField(to='miniapp.benefits'),
        ),
    ]
